<a href="https://colab.research.google.com/github/ikatyszko/data-science-bootcamp/blob/main/algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
v = np.array([-1,4])

In [4]:
np.linalg.norm(v)

4.123105625617661

In [5]:
v2 = np.array([-10,10,13])

In [7]:
np.linalg.norm(v2)

19.209372712298546

In [8]:
p = np.array([3,0])
q= np.array([0,4])


In [9]:
np.linalg.norm(p-q)

5.0

In [10]:
p = np.array([3,0,1])
q= np.array([0,4,2])

In [11]:
np.linalg.norm(p-q)

5.0990195135927845

In [2]:
X = np.array([[5,3],[3,9]])
Y = np.array([[1],[-1]])

In [3]:
X@Y

array([[ 2],
       [-6]])

In [4]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

In [5]:
X.dot(Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

In [7]:
A = np.array([[2,4],[-1,3]])

In [9]:
round(np.linalg.det(A))

10

In [10]:
np.trace(A)

5

In [11]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [13]:
B = np.linalg.inv(A)

In [14]:
print(B)

[[ 0.3 -0.4]
 [ 0.1  0.2]]


In [23]:
np.set_printoptions(precision=4,suppress=True)


In [24]:
A.dot(B)

array([[1., 0.],
       [0., 1.]])

In [25]:
B.dot(A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [26]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [27]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [28]:
AA = np.array([[2,4],[1,-1]])
BB = np.array([[10],[-1]])

In [29]:
AT = np.linalg.inv(AA)

In [31]:
X = AT.dot(BB)

In [32]:
X.shape

(2, 1)