<a href="https://colab.research.google.com/github/ikatyszko/data-science-bootcamp/blob/main/numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('Hello World')

Hello World


In [3]:
pip install numpy

In [6]:
import numpy as np

In [7]:
np.__version__

'1.21.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [14]:
x = np.array([1,3])

In [15]:
x

array([1, 3])

In [16]:
print(x)

[1 3]


In [18]:
type(x)

numpy.ndarray

In [19]:
z = np.array([1.2, 1.1, 1.4])

In [20]:
print(z)

[1.2 1.1 1.4]


In [22]:
z.dtype

dtype('float64')

In [8]:
x = np.array([[1,2], [-3,1]])

In [9]:
x.ndim

2

In [10]:
x.shape

(2, 2)

In [12]:
x.dtype

dtype('int64')

In [15]:
x = np.array([[1,2,4],[3,4,5]])

In [16]:
print(x)

[[1 2 4]
 [3 4 5]]


In [19]:
x =np.array(
    [[[1,2,3],[2,4,6]],
     [[2,2,3],[7,8,9]]]
)

In [20]:
x

array([[[1, 2, 3],
        [2, 4, 6]],

       [[2, 2, 3],
        [7, 8, 9]]])

In [21]:
x.ndim

3

In [22]:
x.shape

(2, 2, 3)

In [24]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [25]:
B = np.array([1 ,5 ,6], dtype=float)

In [26]:
B

array([1., 5., 6.])

In [27]:
Z = np.array([True,False,True])
Z.dtype

dtype('bool')

In [31]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
np.full(shape=(3,3), fill_value=4, dtype= 'int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [39]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [41]:
np.arange(start=10,stop=100,step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
np.linspace(start=1,stop=10,num =7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [44]:
B = np.arange(15)

In [45]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
B.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
B.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
A = np.array([1, 3, 4, 5])
B = np.array([1,5,-5,6])

In [50]:
A+B

array([ 2,  8, -1, 11])

In [51]:
A*B

array([  1,  15, -20,  30])

In [52]:
A-B

array([ 0, -2,  9, -1])

In [53]:
A/B

array([ 1.        ,  0.6       , -0.8       ,  0.83333333])

In [54]:
A +  3*B

array([  4,  18, -11,  23])

In [55]:
np.add(A,B)
np.subtract(A,B)
np.multiply(A,B)
np.divide(A,B)

array([ 1.        ,  0.6       , -0.8       ,  0.83333333])

In [59]:
Z = np.array([[1,3],[-2,0]])
Y = np.array([[6,0],[-1,2]]) 
print(Z, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [61]:
np.dot(Z,Y)

array([[  3,   6],
       [-12,   0]])

In [63]:
Z.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [64]:
Z @ Y

array([[  3,   6],
       [-12,   0]])

In [65]:
np.random.seed(0)

In [69]:
np.random.randn()

0.7415917408091613

In [70]:
np.random.randn(10)

array([ 1.55291372, -2.2683282 ,  1.33354538, -0.84272405,  1.96992445,
        1.26611853, -0.50587654,  2.54520078,  1.08081191,  0.48431215])

In [71]:
np.random.randn(10,4)

array([[ 0.57914048, -0.18158257,  1.41020463, -0.37447169],
       [ 0.27519832, -0.96075461,  0.37692697,  0.03343893],
       [ 0.68056724, -1.56349669, -0.56669762, -0.24214951],
       [ 1.51439128, -0.3330574 ,  0.04736482,  1.46274045],
       [ 1.53502913,  0.56644004,  0.14926509, -1.078278  ],
       [ 1.39547227,  1.78748405, -0.56951726,  0.17538653],
       [-0.46250554, -1.0858006 ,  0.63973599, -0.38586334],
       [-0.77576235,  0.99571135, -1.93320478,  0.24853063],
       [-0.03124534, -0.13947396, -0.19065598,  0.44863753],
       [-0.99242977, -0.22593966, -1.65457077, -0.63972264]])

In [73]:
np.random.rand(10)

array([0.65632959, 0.13818295, 0.19658236, 0.36872517, 0.82099323,
       0.09710128, 0.83794491, 0.09609841, 0.97645947, 0.4686512 ])

In [77]:
np.random.randint(low=10, high=101,size=10)

array([83, 10, 20, 53, 68, 33, 69, 12, 72, 45])

In [82]:
np.random.choice([1,2,3])

3

In [83]:
np.random.choice(['zlo','okno'])

'zlo'

In [84]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
Q = np.array([1,4,5,8])
Z = np.array([-1,6,8,0])

In [86]:
np.exp(1)

2.718281828459045

In [87]:
np.sqrt(9)

3.0

In [88]:
  np.all([2,3,1])

True

In [90]:
np.any([0,3,4])

True

In [96]:
L= np.random.rand(5)

In [97]:
np.argmax(L)

3

In [99]:
L[np.argmax(A)]

0.13179786240439217

In [100]:
np.argmin(L)

3

In [101]:
np.argsort(L)

array([3, 1, 2, 4, 0])

In [103]:
np.max(L)

0.9292961975762141

In [104]:
np.min(L)

0.13179786240439217

In [106]:
np.mean(L)

0.5526801193028354

In [108]:
np.median(L)

0.6674103799636817

In [109]:
np.std(L)

0.2876570819953911

In [7]:
AA = np.arange(20)

In [117]:
AA[7]
AA[1:3]

array([1, 2])

In [8]:
AA= AA.reshape(4,-1)

In [122]:
print(AA)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [123]:
AA[0]

array([0, 1, 2, 3, 4])

In [124]:
AA[:,0]

array([ 0,  5, 10, 15])

In [125]:
AA[1,1]

6

In [9]:
for item in AA:
  print(item)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
for item in AA.flat:
  print(item)

In [11]:
AA.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
AA.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [14]:
K= np.arange(start=-10,stop=10,step=0.5)

In [17]:
K = K.reshape(10,-1)

In [18]:
K>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [19]:
K[K>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [23]:
np.bitwise_and(K > -5, K < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [24]:
K[np.bitwise_and(K > -5, K < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [25]:
np.bitwise_or(K >-2, K<7)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])